name: clreader
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  url_launcher: ^4.0.3
  scoped_model: ^1.0.1
  clipboard_manager: ^0.0.4
  shared_preferences: ^0.4.3
  flutter_advanced_networkimage: any
  sqflite: ^1.0.0
  dio: ^1.0.14
  html: any
  gbk2utf8: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/pics/alipay.jpg

analyzer:
  strong-mode: true
  language:
    enableSuperMixins: true